# Generated by Django 3.1.7 on 2021-04-01 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('port', models.IntegerField()),
                ('timeout', models.IntegerField(choices=[(0.5, 0.5), (1, 1), (5, 5), (10, 10)], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('msg', models.CharField(max_length=100)),
                ('enable', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('fan_speed', models.IntegerField()),
                ('fan_percent', models.IntegerField()),
                ('gpu_clock', models.IntegerField()),
                ('memory_clock', models.IntegerField()),
                ('gpu_voltage', models.FloatField()),
                ('gpu_activity', models.IntegerField()),
                ('mhs', models.FloatField()),
                ('mhs_30s', models.FloatField()),
                ('accepted', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('error', models.IntegerField()),
                ('informer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.informer')),
            ],
        ),
    ]
