# Generated by Django 3.1.7 on 2021-04-01 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20210321_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('msg', models.CharField(max_length=100)),
                ('enable', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('fan_speed', models.IntegerField()),
                ('fan_percent', models.IntegerField()),
                ('gpu_clock', models.IntegerField()),
                ('memory_clock', models.IntegerField()),
                ('gpu_voltage', models.FloatField()),
                ('gpu_activity', models.IntegerField()),
                ('mhs', models.FloatField()),
                ('mhs_30s', models.FloatField()),
                ('accepted', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('error', models.IntegerField()),
                ('informer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.informer')),
            ],
        ),
    ]
